import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "This will serve as the default title for all.",
    template: "%s | Code Academy",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
        <header style={{ backgroundColor: "red", color: "fff", flex: "1" }}>
          <p>This is the website header.</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "red", color: "fff", flex: "1" }}>
          <p>This is the website footer.</p>
        </footer>
      </body>
    </html>
  );
}
